### ISSUE TITLE
grunt platform:add:android时报错

### ISSUE THREAD

**Issue by zhaoshiling1017** [lanceli/cnodejs-ionic#37]
Installing "cordova-plugin-badge" for android

> > Failed to install 'cordova-plugin-badge':CordovaError: Plugin doesn't support this project's cordova-android version. cordova-android: 3.5.1, failed version requirement: >=4
> >     at checkEngines (/home/lenzhao/dev/ionic/cnodejs-ionic/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:117:29)
> >     at _fulfilled (/home/lenzhao/dev/ionic/cnodejs-ionic/node_modules/cordova/node_modules/q/q.js:798:54)
> >     at self.promiseDispatch.done (/home/lenzhao/dev/ionic/cnodejs-ionic/node_modules/cordova/node_modules/q/q.js:827:30)
> >     at Promise.promise.promiseDispatch (/home/lenzhao/dev/ionic/cnodejs-ionic/node_modules/cordova/node_modules/q/q.js:760:13)
> >     at /home/lenzhao/dev/ionic/cnodejs-ionic/node_modules/cordova/node_modules/q/q.js:574:44
> >     at flush (/home/lenzhao/dev/ionic/cnodejs-ionic/node_modules/cordova/node_modules/q/q.js:108:17)
> >     at nextTickCallbackWith0Args (node.js:415:9)
> >     at process._tickCallback (node.js:344:13)
> > Plugin doesn't support this project's cordova-android version. cordova-android: 3.5.1, failed version requirement: >=4
> > Warning: Task "platform:add:android" failed. Use --force to continue.

Aborted due to warnings.

**Comment by lukertty** [comment]
same

**Comment by zhyzhy782** [comment]
Hi,
Have you  ever  seen that  amazing  stuff?  That's so interesting, please take a look http://black.flyrc101.com/e7piw/43

My best to you, zhyzhy782
